### ISSUE TITLE
Why the specific dependency on Go `1.21.9`?

### ISSUE THREAD

**Issue by stgraber** [openfga/go-sdk#94]
### Checklist

- [X] I have looked into the [README](https://github.com/openfga/go-sdk/blob/main/README.md) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/openfga/go-sdk/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/openfga/go-sdk/releases/latest) of OpenFGA and the issue still persists.
- [X] I have searched the [Slack community](https://openfga.dev/community) and have not found a suitable solution or answer.
- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Description

Hello,

I see that a recent change which then made it into 0.3.6 has caused a bump of Go from 1.21 to 1.21.9 but I can't figure out why.

This bump is preventing us from consuming 0.3.6 from within Incus as our base is still 1.21.

### Expectation

Be able to build with Go 1.21.x

### Reproduction

Build or consume go-sdk from a project using Go 1.21.x < 1.21.9.

### OpenFGA SDK version

0.3.6

### OpenFGA version

irrelevant

### SDK Configuration

irrelevant

**Comment by rhamzeh** [comment]
Hi @stgraber - Will have chat with the team before reverting around this. We can bump it up in CI, but that means that folks running earlier builds of Go may be vulnerable.

If we agree on this path, we'll revert to 1.21 next week - sorry for this.

Main reason for the bump is Go's vulnerability reporting. It was raising errors on the CI.

If I am not mistaken, this issue is what triggered govulncheck for us, https://github.com/golang/go/issues/65065. Fixed in Go 1.21.8.

On one hand we can say the choice of the runtime should be up to the user, but we're usually erring a lot on the side of caution.

Apologies if it takes us a bit of time to get back on this, I'd rather not revert without a team consensus.

**Comment by rhamzeh** [comment]
Hi @stgraber - just an update, we agreed to revert to 1.21 - sorry for the delay and the noise. A release with this fix should go out tomorrow.

**Comment by stgraber** [comment]
Thanks!

**Comment by rhamzeh** [comment]
v0.3.7 is now out - thanks @stgraber!

**Comment by stgraber** [comment]
thanks!
